---
- name: Prairie single-node Rancher deployment
  hosts: cattle
  become: true
  gather_facts: true
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  roles:
    - base
    - k3s
#    - rancher
#    - tls
